protected/models/Clientevisita.php
<?php

/**
 * This is the model class for table "clientevisita".
 *
 * The followings are the available columns in table 'clientevisita':
 * @property string $id
 * @property string $idCliente
 * @property string $fechaVisita
 * @property string $confirmado
 * @property string $usuario
 * @property string $observacion
 * @property string $idEmpleado
 * @property string $idQuejaSugerencia
 * @property string $tipo
 * @property string $idCatTipoVisita
 * @property string $estatus
 * @property string $idClienteVisita
 * @property string $fechaAtencion
 * @property string $usuarioAtencion
 * @property string $idCatTono
 *
 * The followings are the available model relations:
 * @property Cliente $idCliente0
 * @property Empleado $idEmpleado0
 * @property Quejasugerencia $idQuejaSugerencia0
 * @property Cattipovisita $idCatTipoVisita0
 * @property Clientevisita $idClienteVisita0
 * @property Clientevisita[] $clientevisitas
 * @property Cattono $idCatTono0
 * @property Clientevisitainvitado[] $clientevisitainvitados
 * @property Clientevisitaseguimiento[] $clientevisitaseguimientos
 */
class Clientevisita extends CActiveRecord
{
    public $_horaVisita;
    public $_horaAtencion;
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'clientevisita';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('idCliente, fechaVisita,  confirmado, usuario, observacion, idEmpleado, tipo, idCatTipoVisita, estatus', 'required'),
			array('idCliente, idEmpleado, idQuejaSugerencia, idCatTipoVisita, idClienteVisita, idCatTono', 'length', 'max'=>10),
			array('confirmado, tipo, estatus', 'length', 'max'=>1),
			array('usuario, usuarioAtencion', 'length', 'max'=>45),
			array('fechaAtencion,_horaVisita, _horaAtencion,', 'safe'),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
            array('fechaAtencion, idCatTono, usuarioAtencion', 'required','on'=>'finaliza'),
			array('id, idCliente, fechaVisita, confirmado, usuario, observacion, idEmpleado, idQuejaSugerencia, tipo, idCatTipoVisita, estatus, idClienteVisita, fechaAtencion, usuarioAtencion, idCatTono', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'idCliente0' => array(self::BELONGS_TO, 'Cliente', 'idCliente'),
			'idEmpleado0' => array(self::BELONGS_TO, 'Empleado', 'idEmpleado'),
			'idQuejaSugerencia0' => array(self::BELONGS_TO, 'Quejasugerencia', 'idQuejaSugerencia'),
			'idCatTipoVisita0' => array(self::BELONGS_TO, 'Cattipovisita', 'idCatTipoVisita'),
			'idClienteVisita0' => array(self::BELONGS_TO, 'Clientevisita', 'idClienteVisita'),
			'clientevisitas' => array(self::HAS_MANY, 'Clientevisita', 'idClienteVisita'),
			'idCatTono0' => array(self::BELONGS_TO, 'Cattono', 'idCatTono'),
			'clientevisitainvitados' => array(self::HAS_MANY, 'Clientevisitainvitado', 'idClienteVisita'),
			'clientevisitaseguimientos' => array(self::HAS_MANY, 'Clientevisitaseguimiento', 'idClienteVisita'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'idCliente' => 'Id Cliente',
			'fechaVisita' => 'Fecha Visita',
			'confirmado' => 'Estatus de la Visita, ',
			'usuario' => 'Usuario',
			'observacion' => 'Observacion',
			'idEmpleado' => 'Id Empleado',
			'idQuejaSugerencia' => 'Id Queja Sugerencia',
			'tipo' => 'Selecciona un tipo de Registro, ',
			'idCatTipoVisita' => 'Selecciona Tipo Visita',
			'estatus' => 'Estatus',
			'idClienteVisita' => 'Id Cliente Visita',
			'fechaAtencion' => 'Fecha Atencion',
			'usuarioAtencion' => 'Usuario Atencion',
			'idCatTono' => 'Selecciona un Tono, ',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('idCliente',$this->idCliente,true);
		$criteria->compare('fechaVisita',$this->fechaVisita,true);
		$criteria->compare('confirmado',$this->confirmado,true);
		$criteria->compare('usuario',$this->usuario,true);
		$criteria->compare('observacion',$this->observacion,true);
		$criteria->compare('idEmpleado',$this->idEmpleado,true);
		$criteria->compare('idQuejaSugerencia',$this->idQuejaSugerencia,true);
		$criteria->compare('tipo',$this->tipo,true);
		$criteria->compare('idCatTipoVisita',$this->idCatTipoVisita,true);
		$criteria->compare('estatus',$this->estatus,true);
		$criteria->compare('idClienteVisita',$this->idClienteVisita,true);
		$criteria->compare('fechaAtencion',$this->fechaAtencion,true);
		$criteria->compare('usuarioAtencion',$this->usuarioAtencion,true);
		$criteria->compare('idCatTono',$this->idCatTono,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Clientevisita the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/ClientevisitaController.php
<?php

class ClientevisitaController extends Controller
{
	/**
	 * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
	 * using two-column layout. See 'protected/views/layouts/column2.php'.
	 */
	public $layout='//layouts/main';

	/**
	 * @return array action filters
	 */
	public function filters()
	{
		return array(
			'accessControl', // perform access control for CRUD operations
			'postOnly + delete', // we only allow deletion via POST request
		);
	}

	/**
	 * Specifies the access control rules.
	 * This method is used by the 'accessControl' filter.
	 * @return array access control rules
	 */
	public function accessRules()
	{
		return array(
			array('allow',  // allow all users to perform 'index' and 'view' actions
				'actions'=>array('index','create','createConCliente','view','CreateConIdVisita'),
				'users'=>array('*'),
			),
			array('deny',  // deny all users
				'users'=>array('*'),
			),
		);
	}

	public function actionIndex() {
        $criteria = new CDbCriteria;
        $busqueda = new Clientevisita;

        /*if (isset($_POST["btnNuevo"])) {

            if (isset($_POST['Catcolonia'])) {
                $new->attributes = $_POST['Catcolonia'];
                $new->usuario = Yii::app()->user->nombre_usuario;

                if ($new->validate()) {
                    if ($new->save()) {
                        Yii::app()->user->setFlash('success', 'El Registro ha sido realizado.');
                        $this->redirect(array('index'));
                    }
                }
            }
        }*/

        if (!empty($_GET['Clientevisita'])) {
            $busqueda->attributes = $_GET['Clientevisita'];
            if(!empty($busqueda->fechaVisita)){
                $fechaInicio=$busqueda->fechaVisita;
            }
        }elseif(isset($_GET['fechaInicio']) && !empty($_GET['fechaInicio'])){
			$fechaInicio=$_GET['fechaInicio'];
        }
        

        $arrayMeses = array('Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre');
        $empleados = CHtml::listData(Viewempleado::model()->findAll(),'id','nombre');

        $estaSemana=array();
        if(isset($fechaInicio)){
            if(date('N',strtotime($fechaInicio))==1){
                $estaSemana[]=$arrayMeses[date('n',strtotime($fechaInicio))-1].' '.date('j',strtotime($fechaInicio));
                $estaSemanaID[]=date('Y-m-d',strtotime($fechaInicio));
                $estaSemanaCompleto=strtotime(date('Y-m-d',strtotime($fechaInicio)));
            }else{
                $estaSemana[]=$arrayMeses[date('n',strtotime($fechaInicio))-1].' '.date('j',strtotime('last monday',strtotime($fechaInicio)));
                $estaSemanaID[]=date('Y-m-d',strtotime('last monday',strtotime($fechaInicio)));
                $estaSemanaCompleto=strtotime(date('Y-m-d',strtotime('last monday',strtotime($fechaInicio))));
            }
        }else{
            if(date('N')==1){
                $estaSemana[]=$arrayMeses[date('n')-1].' '.date('j');
                $estaSemanaID[]=date('Y-m-d');
                $estaSemanaCompleto=strtotime(date('Y-m-d'));
            }else{
                $estaSemana[]=$arrayMeses[date('n')-1].' '.date('j',strtotime('last monday'));
                $estaSemanaID[]=date('Y-m-d',strtotime('last monday'));
                $estaSemanaCompleto=strtotime(date('Y-m-d',strtotime('last monday')));
            }
        }
        for($i=1;$i<=6;$i++){
            $estaSemana[]=$arrayMeses[date('n',strtotime('+'.$i.' day',$estaSemanaCompleto))-1].' '.date('j',strtotime('+'.$i.' day',$estaSemanaCompleto));
            $estaSemanaID[]=date('Y-m-d',strtotime('+'.$i.' day',$estaSemanaCompleto));
        }

        $this->render('index', array(
            //'new' => $new,
            'busqueda' => $busqueda,
            //'catalogo' => $catalogo,
            'estaSemana' => $estaSemana,
            'estaSemanaID' => $estaSemanaID,
            'estaSemanaCompleto' => $estaSemanaCompleto,
            'arrayMeses' => $arrayMeses,
            'empleados' => $empleados,

        ));
	}
	
	public function actionCreate() {

        $criteria = new CDbCriteria;
        $ClienteBusqueda = new Viewcliente();
        if (isset($_POST['Viewcliente'])) {
            $ClienteBusqueda->attributes = $_POST['Viewcliente'];
            if (isset($ClienteBusqueda->idCatTipoCliente)) {
                $criteria->compare("idCatTipoCliente", $ClienteBusqueda->idCatTipoCliente);
            }
            if (isset($ClienteBusqueda->categoria)) {
                $criteria->compare("categoria", $ClienteBusqueda->categoria);
            }
            if (isset($ClienteBusqueda->idCatSector)) {
                $criteria->compare("idCatSector", $ClienteBusqueda->idCatSector);
            }
            if (isset($ClienteBusqueda->idCatPonderacion)) {
                $criteria->compare("idCatPonderacion", $ClienteBusqueda->idCatPonderacion);
            }
            if (isset($ClienteBusqueda->idCatFuenteContratacion)) {
                $criteria->compare("idCatFuenteContratacion", $ClienteBusqueda->idCatFuenteContratacion);
            }
            if (isset($ClienteBusqueda->estatus)) {
                $criteria->compare("estatus", $ClienteBusqueda->estatus);
            }

            if (isset($ClienteBusqueda->fechaAlta)) {
                if ($_POST['Viewunidad']['fechaAlta'] != "") {
                    $dtFechaI = date_format(date_create(str_replace("/", "-", $_POST['Viewunidad']['fechaAlta'])), "Y-m-d");
                    $dtFechaF = date_format(date_create(str_replace("/", "-", $_POST['Viewunidad']['fechaAltaFin'])), "Y-m-d");

                    $criteria->addBetweenCondition("fechaAlta", $dtFechaI . ' 00:00:00', $dtFechaF . ' 23:59:59');
                }
            }
        }



        $Clientes = Viewcliente::model()->findAll($criteria);

        $this->render('create', array(
            'Clientes' => $Clientes,
            'ClienteBusqueda' => $ClienteBusqueda,
        ));
    }

    public function actionEliminar($id) {
        $modelDelete = Catcolonia::model()->findByPk($id);
        if (!empty($modelDelete)) {
            try {
                $modelDelete->delete();
                Yii::app()->user->setFlash('success', 'El Registro ha sido eliminado.');
            } catch (Exception $e) {
                Yii::app()->user->setFlash('error', 'El Registro no puede ser eliminado debido a que existe una relación con algun otro catálogo.');
            }
        } else {
            Yii::app()->user->setFlash('error', 'El Registro no puede ser eliminado debido a que no existe su ID.');
        }
        $this->redirect(array('index'));
    }

    public function actionCreateConCliente() {
        $cliente = Cliente::model()->findByPk($_GET['idCliente']);
        $visita = new Clientevisita;
        $empleados = CHtml::listData(Viewempleado::model()->findAll(),'id','nombre');

        if (isset($_POST["Clientevisita"])) {
            //var_dump($_POST);die;
            $visita->attributes = $_POST["Clientevisita"];
            $fechaVisita=$visita->fechaVisita." ".$visita->_horaVisita.":00";
           // var_dump($fechaVisita);die;

            $visita->idCliente = $cliente->id;
            $visita->usuario = Yii::app()->user->nombre_usuario;
            $visita->estatus = "P";
            $visita->fechaVisita=$fechaVisita;
            if ($visita->save()) {
                $this->redirect(CController::createUrl('clientevisita/view', array('id' => $visita->id)));
            }
            $visita->fechaVisita=$_POST["Clientevisita"]["fechaVisita"];
        }
        $this->render('createConCliente', array(
            'cliente' => $cliente,
            'visita' => $visita,
            'empleados'=>$empleados,
        ));
    }

    public function actionCreateConIdVisita($id) {
        $visita = new Clientevisita;
        $oldVisita= CLientevisita::model()->findByPk($id);
        $cliente = Cliente::model()->findByPk($oldVisita->idCliente);
        $visita->idClienteVisita=$oldVisita->id;
        $visita->tipo = $oldVisita->tipo;
        $visita->idEmpleado = $oldVisita->idEmpleado;
        $visita->idCatTipoVisita = $oldVisita->idCatTipoVisita;
        $empleados = CHtml::listData(Viewempleado::model()->findAll(),'id','nombre');

        if (isset($_POST["Clientevisita"])) {
            //var_dump($_POST);die;
            $visita->attributes = $_POST["Clientevisita"];
            $visita->idCliente = $cliente->id;
            $visita->usuario = Yii::app()->user->nombre_usuario;
            $visita->tipo = $oldVisita->tipo;
            $visita->estatus = "P";
            $visita->fechaVisita="{$visita->fechaVisita} {$visita->_horaVisita}:00";
            if ($visita->save()) {
                $oldVisita->estatus='R';
                $oldVisita->update();
                $this->redirect(CController::createUrl('clientevisita/view', array('id' => $visita->id)));
            }
            $visita->fechaVisita=$_POST["Clientevisita"]["fechaVisita"];
        }
        $this->render('createConCliente', array(
            'cliente' => $cliente,
            'visita' => $visita,
            'empleados'=>$empleados,
        ));
    }

    public function actionView($id) {
	    $updateVisita=$this->loadModel($id);
        $visita = ViewClienteVisita::model()->find("id=:id",array(":id" => $id));
        $seguimiento= new Clientevisitaseguimiento();
        $nuevoInvitado=new Clientevisitainvitado();
        $criteria=new CDbCriteria();
        $criteria->compare("idClienteVisita",$id);

        $criteria->order="fechaAlta DESC";
        $seguimientos= Clientevisitaseguimiento::model()->findAll($criteria);
        $empleados = CHtml::listData(Viewempleado::model()->findAll(),'id','nombre');
        $criteriaVs=new CDbCriteria();
        $criteriaVs->compare("id",$id);

protected/views/clientevisita/createConCliente.php
<style>
    .select2-container--default .select2-selection--single .select2-selection__arrow b {
        border-color: #fff transparent transparent transparent;
    }
    .select2-container--default .select2-selection--single .select2-selection__arrow {
        top: 10px;
        right: 15px;
    }
    .select2-container {
        width: 100% !important;
    }
    .select2-container--default .select2-selection--single {
        color: #fff;
        height: auto;
    }
    .select2-container--default .select2-selection--single .select2-selection__rendered {
        background-color: white ;
        color: #535251;
        height: 36px;
        padding: 4px 30px 8px 20px;
    }
</style>
<div class="page-wrapper">
    <!-- Page-header start -->
    <div class="page-header card">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="icofont icofont-ui-user bg-warning"></i>

                    <div class="d-inline">
                        <h4><?= getTxtCte($cliente->id) ?> - <?= ucwords(mb_strtolower($cliente->nombre)) ?> (Nueva Visita)</h4>
                        <span>Ingrese toda la información de los campos requeridos para registrar la cotización.</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4">
                <div class="page-header-breadcrumb">
                    <ul class="breadcrumb-title">
                        <li class="breadcrumb-item">
                            <a href="index.html">
                                <i class="icofont icofont-home"></i>
                            </a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">Visitas</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">Nueva Visita</a>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <!-- Page-header end -->


    <!-- Page-body start -->
    <div class="page-body">

        <div class="row">
            <div class="col-lg-12">


                <?php
                $form = $this->beginWidget('CActiveForm', array(
                    'id' => 'login-form',
                    'enableClientValidation' => true,
                    'clientOptions' => array(
                        'validateOnSubmit' => true,
                    ),
                ));
                ?>
                <div class="card">
                    <div class="card-header bg-warning">
                        <h5 class="text-white">Información General</h5>
                        <div class="card-header-right" style="margin-right: 10px;">
                            <a href="<?= CController::createUrl('clientevisita/index') ?>"><button class="btn btn-sm btn-warning btn-out-dashed" type="button">SALIR</button></a>
                        </div>
                    </div>
                    <div class="card-body">
                        <?php
                        if (!empty($visita->errors)) {
                            ?>
                            <div class="alert alert-danger icons-alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                    <i class="icofont icofont-close-line-circled"></i>
                                </button>
                                <p><strong>Atención!</strong> <?= $form->errorSummary($visita) ?></p>
                            </div>

                            <?php
                        }
                        ?>
                        <div style="padding-left: 30px; padding-right: 30px;padding-top: 20px;padding-bottom: 10px;">
                            <div class="row">
                                <div class="col-lg-3 col-md-12 m-b-15" >
                                    <label class="text-muted" >Fecha de Visita</label>
                                    <?php
                                    if($visita->fechaVisita==""){
                                        $visita->fechaVisita=date("Y-m-d");
                                    }
                                    echo $form->dateField($visita, 'fechaVisita', array('class' => "form-control",
                                        'placeholder' => "Fecha Visita",
                                        'value' => $visita->fechaVisita,
                                        'title' => "Fecha Visita")); ?>
                                </div>
                                <div class="col-lg-3 col-md-12 m-b-15">
                                    <label class="text-muted" >Hora de Visita</label>
                                    <?php
                                    if($visita->_horaVisita==""){
                                        $visita->_horaVisita=date("H:i");
                                    }

                                    echo $form->timeField($visita, '_horaVisita', array('class' => "form-control", 'placeholder' => "Hora Visita", 'title' => "Hora Visita",'min'=>"8:00", 'max'=>"18:00")); ?>
                                </div>
                                <div class="col-lg-6 col-md-12 m-b-15">
                                    <label class="text-muted" >Empleado</label>
                                    <?php echo $form->dropDownList($visita, 'idEmpleado', $empleados, array('class' => "js-example-basic-single col-sm-12",
                                        'empty' => "-- Selecciona una opción -- ")); ?>
                                </div>
                                <div class="col-lg-4 col-md-12 m-b-15">
                                    <label class="text-muted" >Tipo de Visita</label>
                                    <?php
                                    $tipoVisita = CHtml::listData(Cattipovisita::model()->findAll(), 'id', 'descripcion');
                                    echo $form->dropDownList($visita, 'idCatTipoVisita', $tipoVisita, array('class' => "form-control", 'empty' => "Tipo de Visita"));
                                    ?>
                                </div>
                                <div class="col-lg-4 col-md-12 m-b-15">
                                    <label class="text-muted" >Estatus de la Visita</label>
                                    <?php
                                    echo $form->dropDownList($visita, 'confirmado', array("S" => "CONFIRMADO","N" => "POR CONFIRMAR"), array('class' => "form-control", 'empty' => "-- Selecciona una opción --"));
                                    ?>
                                </div>
                                <div class="col-lg-4 col-md-12 m-b-15">
                                    <label class="text-muted" >Tipo de Registro</label>
                                    <?php
                                    echo $form->dropDownList($visita, 'tipo', array("P" => "PROACTIVO","E" => "EN RESPUESTA"), array('class' => "form-control", 'empty' => "-- Selecciona una opción --"));
                                    ?>
                                </div>

                            </div>

                            <div class="row">

                                <div class="col-lg-12 col-md-12 m-b-15">
                                    <label class="text-muted" >Observaciones, Comentarios o Adjuntos</label>
                                    <?php echo $form->textArea($visita, 'observacion', array('class' => "form-control", 'rows' => "3", 'placeholder' => "Observación", 'title' => "Observación")); ?>
                                </div>
                            </div>

                            <div class="row float-right mt-2">
                                <div class="col-lg-12 col-md-12 m-b-15">
                                    <button class="btn btn-sm btn-warning sendForm" type="submit"  ><i class="fas fa-save mr-2"></i> Guardar Visita</button>
                                </div>

                            </div>
                        </div>


                    </div>
                </div>



                <?php $this->endWidget(); ?>
                <!-- tab content end -->
            </div>
        </div>

    </div>
    <!-- Page-body end -->
</div>
<script>
    $(document).ready(function(){
        // Single Search Select
        $(".js-example-basic-single").select2();
    });
</script>