protected/models/Catmetodocontacto.php
<?php

/**
 * This is the model class for table "catmetodocontacto".
 *
 * The followings are the available columns in table 'catmetodocontacto':
 * @property string $id
 * @property string $descripcion
 * @property string $usuario
 * @property string $fechaAlta
 *
 * The followings are the available model relations:
 * @property Quejasugerencia[] $quejasugerencias
 */
class Catmetodocontacto extends CActiveRecord
{
	/**
	 * @return string the associated database table name
	 */
	public function tableName()
	{
		return 'catmetodocontacto';
	}

	/**
	 * @return array validation rules for model attributes.
	 */
	public function rules()
	{
		// NOTE: you should only define rules for those attributes that
		// will receive user inputs.
		return array(
			array('descripcion, usuario, fechaAlta', 'required'),
			array('descripcion', 'length', 'max'=>120),
			array('usuario', 'length', 'max'=>45),
			// The following rule is used by search().
			// @todo Please remove those attributes that should not be searched.
			array('id, descripcion, usuario, fechaAlta', 'safe', 'on'=>'search'),
		);
	}

	/**
	 * @return array relational rules.
	 */
	public function relations()
	{
		// NOTE: you may need to adjust the relation name and the related
		// class name for the relations automatically generated below.
		return array(
			'quejasugerencias' => array(self::HAS_MANY, 'Quejasugerencia', 'idCatMetodoContacto'),
		);
	}

	/**
	 * @return array customized attribute labels (name=>label)
	 */
	public function attributeLabels()
	{
		return array(
			'id' => 'ID',
			'descripcion' => 'Descripcion',
			'usuario' => 'Usuario',
			'fechaAlta' => 'Fecha Alta',
		);
	}

	/**
	 * Retrieves a list of models based on the current search/filter conditions.
	 *
	 * Typical usecase:
	 * - Initialize the model fields with values from filter form.
	 * - Execute this method to get CActiveDataProvider instance which will filter
	 * models according to data in model fields.
	 * - Pass data provider to CGridView, CListView or any similar widget.
	 *
	 * @return CActiveDataProvider the data provider that can return the models
	 * based on the search/filter conditions.
	 */
	public function search()
	{
		// @todo Please modify the following code to remove attributes that should not be searched.

		$criteria=new CDbCriteria;

		$criteria->compare('id',$this->id,true);
		$criteria->compare('descripcion',$this->descripcion,true);
		$criteria->compare('usuario',$this->usuario,true);
		$criteria->compare('fechaAlta',$this->fechaAlta,true);

		return new CActiveDataProvider($this, array(
			'criteria'=>$criteria,
		));
	}

	/**
	 * Returns the static model of the specified AR class.
	 * Please note that you should have this exact method in all your CActiveRecord descendants!
	 * @param string $className active record class name.
	 * @return Catmetodocontacto the static model class
	 */
	public static function model($className=__CLASS__)
	{
		return parent::model($className);
	}
}

protected/controllers/CatmetodocontactoController.php
<?php

class CatmetodocontactoController extends Controller {

    /**
     * @var string the default layout for the views. Defaults to '//layouts/column2', meaning
     * using two-column layout. See 'protected/views/layouts/column2.php'.
     */
    public $layout = '//layouts/main';

    /**
     * @return array action filters
     */
    public function filters() {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules() {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index','Eliminar'),
                'users' => array('@'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    /**
     * Lists all models.
     */
    public function actionIndex() {
        $criteria = new CDbCriteria;
        $new = new Catmetodocontacto;
        $busqueda = new Catmetodocontacto;



        if (isset($_POST["btnNuevo"])) {

            if (isset($_POST['Catmetodocontacto'])) {
                $new->attributes = $_POST['Catmetodocontacto'];
                $new->usuario= Yii::app()->user->nombre_usuario;
                $new->fechaAlta=date('Y-m-d H:i:s');
                
                if ($new->validate()) {
                    if ($new->save()) {
                        Yii::app()->user->setFlash('success', 'El Registro ha sido realizado.');
                        $this->redirect(array('index'));
                    }
                }
            }
        }


        if (isset($_POST["btnBuscar"])) {

            if (isset($_POST['Catmetodocontacto'])){
                $busqueda->attributes = $_POST['Catmetodocontacto'];

                if (isset($busqueda->usuario)) {
                    $criteria->compare("usuario", $busqueda->usuario);
                }
            }
        }
        $catalogo = Catmetodocontacto::model()->findAll(); 
        $this->render('index', array(
            'new' => $new,
            'busqueda' => $busqueda,
            'catalogo' => $catalogo,
        ));
    }
    
    public function actionEliminar($id){
        $modelDelete = Catmetodocontacto::model()->findByPk($id);
        if (!empty($modelDelete)) {
            try {
                $modelDelete->delete();
                Yii::app()->user->setFlash('success', 'El Registro ha sido eliminado.');
            } catch (Exception $e) {
                Yii::app()->user->setFlash('error', 'El Registro no puede ser eliminado debido a que existe una relación con algun otro catálogo.');
            }
        }else{
            Yii::app()->user->setFlash('error', 'El Registro no puede ser eliminado debido a que no existe su ID.');
        }
        $this->redirect(array('index'));
    }

    /**
     * Returns the data model based on the primary key given in the GET variable.
     * If the data model is not found, an HTTP exception will be raised.
     * @param integer $id the ID of the model to be loaded
     * @return Catmetodocontacto the loaded model
     * @throws CHttpException
     */
    public function loadModel($id) {
        $model = Catmetodocontacto::model()->findByPk($id);
        if ($model === null)
            throw new CHttpException(404, 'The requested page does not exist.');
        return $model;
    }

    /**
     * Performs the AJAX validation.
     * @param Catmetodocontacto $model the model to be validated
     */
    protected function performAjaxValidation($model) {
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'catmetodocontacto-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
    }

}

protected/views/catmetodocontacto/index.php
<div class="page-wrapper">
    <!-- Page-header start -->
    <div class="page-header card">
        <div class="row align-items-end">
            <div class="col-lg-8">
                <div class="page-header-title">
                    <i class="icofont icofont-database-add bg-c-blue"></i>

                    <div class="d-inline">
                        <h4>Catálogo de Métodos de Contacto</h4>
                        <span>Administración de catálogos del sistema</span>
                    </div>
                </div>
            </div>
            <div class="col-lg-4 right">

                <div class="page-header-breadcrumb">
                    <ul class="breadcrumb-title">
                        <li class="breadcrumb-item">
                            <a href="index.html">
                                <i class="icofont icofont-home"></i>
                            </a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">Catálogos</a>
                        </li>
                        <li class="breadcrumb-item"><a href="#!">Métodos de Contacto</a>
                        </li>
                    </ul>
                </div>



            </div>
        </div>
    </div>
    <!-- Page-header end -->

    <div class="page-body">

        <!-- Config. table start -->
        <div class="card">
            <div class="card-header">
                <h5>Resultados de la Consulta</h5>
                <span>Se muestran todos los registros del sistema</span>
                <div class="card-header-right" style="margin-right: 10px;">

                    <button class="btn btn-sm btn-info waves-effect"  data-toggle="modal" data-target="#nuevoRegistro" onclick="setNuevo();">NUEVO VALOR</button>
                    <!--<button class="btn btn-sm btn-primary waves-effect"  data-toggle="modal" data-target="#default-Modal">FILTRAR</button>-->
                    <button class="btn btn-sm btn-success waves-effect" >CSV</button>
                    <button class="btn btn-sm btn-danger waves-effect"  >PDF</button>


                </div>
            </div>
            <div class="card-block">
                
            
                
                <div class="">
                    <div class="dt-responsive table-responsive" >
                        <div id="res-config_wrapper" class="dataTables_wrapper dt-bootstrap4 no-footer">
                            <div class="row" >
                                <div class="col-xs-12 col-sm-12 col-lg-12" >
                                    <table width="100%" id="res-config" class="table compact table-striped table-bordered nowrap dataTable no-footer dtr-inline collapsed" role="grid" aria-describedby="res-config_info" style="width: 1544px; font-size: 12px; ">
                                        <thead>
                                        <tr role="row">
                                            <th class="sorting_asc" tabindex="0" aria-controls="res-config" rowspan="1" colspan="1" style="width: 40px;"  aria-sort="ascending" >ID Cátalogo</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="res-config" rowspan="1" colspan="1" style="width: 40px;"  aria-sort="ascending" >Descripción</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="res-config" rowspan="1" colspan="1" style="width: 40px;"  aria-sort="ascending" >Usuario</th>
                                            <th class="sorting_asc" tabindex="0" aria-controls="res-config" rowspan="1" colspan="1" style="width: 40px;"  aria-sort="ascending" >Fecha</th>




                                            <th class="sorting" tabindex="0" aria-controls="res-config" rowspan="1" colspan="1" style="width: 10px; display: none;" aria-label="">-</th>


                                        </tr>
                                        </thead>
                                        <tbody>
                                        <?php
                                        foreach ($catalogo as $item){
                                            ?>
                                            <tr role="row" class="odd">
                                                <td><?=$item->id ?></td>
                                                <td><?=$item->descripcion ?></td>
                                                <td><?=$item->usuario ?></td>
                                                <td><?=$item->fechaAlta ?></td>




                                                <td align="center">
                                                    <?= CHtml::link('<i class="icofont icofont-ui-delete"></i>', CController::createUrl('catmetodocontacto/eliminar',array('id'=>$item->id)), array("class"=>"m-r-15 text-danger",'confirm'=>'Estás seguro de querer eliminar este registro?')); ?>
                                                </td>
                                            </tr>
                                            <?php
                                        }
                                        ?>


                                        </tbody>
                                    </table>
                                    </br>
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- Config. table end -->

    </div>
</div>
<!-- MODAL FILTROS -->
<?php /*<div class="modal fade" id="default-Modal" tabindex="-1" role="dialog" style="z-index: 1050; display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <?php
            $bolError=false;
            $form2 = $this->beginWidget('CActiveForm', array(
                'id' => 'filtrosBusqueda',
                'enableClientValidation' => true,
                'clientOptions' => array(
                    'validateOnSubmit' => true,
                ),
            ));
            ?>
            <div class="modal-header bg-primary" >
                <h4 class="modal-title">Filtros de Búsqueda</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <?php
                if(!empty($busqueda->errors)){
                    $bolError=true;
                    ?>
                    <div class="alert alert-danger icons-alert" >
                        <button type="button" id="errorNewFil" name="errorNewFil" class="close" data-dismiss="alert" aria-label="Close">
                            <i class="icofont icofont-close-line-circled"></i>
                        </button>
                        <p><strong>Atención!</strong> <?=$form2->errorSummary($busqueda) ?></p>
                    </div>

                    <?php
                }
                ?>
                <p>Selecciona uno o varios campos de búsqueda, a continuación presiona 'Aplicar' para ejecutar tu petición.</p>
                <div class="container">
                    <div class="row " >
                        <div class="col-12 m-b-15">
                            <h4 class="sub-title text-muted"><strong>SELECCIONA UNA OPCIÓN</strong></h4>

                            <div class="row">
                                <div class="col-12">
                                    <?php
                                    $tipos = CHtml::listData(Catareaanomalia::model()->findAll(), 'idcatAreaAnomalia', 'descripcion');
                                    echo $form2->dropDownList($catagoloFind2, 'idCatAreaAnomalia', $tipos, array('class' => "form-control", 'placeholder' => "Area Anómalia ...", 'empty' => "Area Anómalia ..."));

                                    ?>
                                </div>
                            </div>

                        </div>

                        <input type="hidden" value="" id="rowElimina" name="rowElimina" >

                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default waves-effect " data-dismiss="modal">CERRAR</button>
                <a href="<?=CController::createUrl('catanomalia/index') ?>"> <button type="button" class="btn btn-sm btn-warning waves-effect waves-light ">LIMPIAR</button></a>
                <button type="submit" class="btn btn-sm btn-primary waves-effect waves-light " id="btnBuscar" name="btnBuscar" value="1">APLICAR</button>
            </div>
            <?php $this->endWidget(); ?>
        </div>
    </div>
</div>*/ ?>


<!-- MODAL NEW -->
<div class="modal fade" id="nuevoRegistro" tabindex="-1" role="dialog" style="z-index: 1050; display: none;" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <?php
            $bolError=false;
            $form = $this->beginWidget('CActiveForm', array(
                'id' => 'login-form',
                'enableClientValidation' => true,
                'clientOptions' => array(
                    'validateOnSubmit' => true,
                ),
            ));
            ?>
            <div class="modal-header bg-info" >
                <h4 class="modal-title">Nuevo método de contacto</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">×</span>
                </button>
            </div>
            <div class="modal-body">
                <?php
                if(!empty($new->errors)){
                    $bolError=true;
                    ?>
                    <div class="alert alert-danger icons-alert" >
                        <button type="button" id="errorNew" name="errorNew" class="close" data-dismiss="alert" aria-label="Close">
                            <i class="icofont icofont-close-line-circled"></i>
                        </button>
                        <p><strong>Atención!</strong> <?=$form->errorSummary($new) ?></p>
                    </div>

                    <?php
                }
                ?>
                <p>Ingrese toda la información que se le solicita.</p>
                <div class="container">
                    <div class="row " >
                        <div class="col-12 m-b-15">
                            <h4 class="sub-title text-muted"><strong>INFORMACIÓN</strong></h4>
                            <div class="row">
                                <div class="col-12 m-b-10">
                                    <?php echo $form->textField($new, 'descripcion', array('class' => "form-control limpiar", 'placeholder' => "Descripción",'title' => "Descripción")); ?>
                                </div>
                            </div>

                        </div>




                    </div>

                </div>

            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-sm btn-default waves-effect " data-dismiss="modal">CERRAR</button>
                <a href="<?=CController::createUrl('catmetodocontacto/index') ?>"> <button type="button" class="btn btn-sm btn-warning waves-effect waves-light ">LIMPIAR</button></a>
                <button type="submit" class="btn btn-sm btn-info waves-effect waves-light " id="btnNuevo" name="btnNuevo" value="1">APLICAR</button>
            </div>
            <?php $this->endWidget(); ?>
        </div>
    </div>
</div>
<?php if($bolError==true){ ?>
    <script>
        window.onload = function() {

            $('#nuevoRegistro').modal('show');
        };

    </script>
<?php } ?>
<script>
    function setNuevo() {
        //LIMPIAR CAMPOS

        $(".limpiar").val("");
        $("#errorNew").click();


    }
</script>
<?php if (Yii::app()->user->hasFlash('error')) { ?>
<script>
    window.onload = function () {
        PNotify.desktop.permission();
        (new PNotify({
            title: 'Cuidado!',
            type: 'danger',
            text: '<?= Yii::app()->user->getFlash('error'); ?>',
            desktop: {
                desktop: true,
                icon: 'assets/images/pnotify/success.png'
            }
        })
                ).get().click(function (e) {
            if ($('.ui-pnotify-closer, .ui-pnotify-sticker, .ui-pnotify-closer *, .ui-pnotify-sticker *').is(e.target))
                return;
            // alert('Hey! You clicked the desktop notification!');
        });
    }


</script>
<?php } ?>
<?php if (Yii::app()->user->hasFlash('success')) { ?>
<script>
    window.onload = function () {
        PNotify.desktop.permission();
        (new PNotify({
            title: 'Proceso Completado!',
            type: 'success',
            text: '<?= Yii::app()->user->getFlash('success'); ?>',
            desktop: {
                desktop: true,
                icon: 'assets/images/pnotify/success.png'
            }
        })
                ).get().click(function (e) {
            if ($('.ui-pnotify-closer, .ui-pnotify-sticker, .ui-pnotify-closer *, .ui-pnotify-sticker *').is(e.target))
                return;
            // alert('Hey! You clicked the desktop notification!');
        });
    }


</script>
<?php } ?>